### ISSUE TITLE
"No games available" appears 1,5 second

### ISSUE THREAD

**Issue by MaryPek** [ludobox/ludobox.github.io#15]
"No games available" appears 1,5 second when you click on browse games and also when you want returned to the main page after saw game's page details.

**Comment by clemsos** [comment]
Yes, this is because as we have more games, the data takes more time to load. The page will wait for the whole data to be loaded before displaying anything. The main problem here is that we still don’t have a database (we use plain files) so we can not optimise data request - with something like lazy loading.

Basically, this will stay like that until we switch towards using a database
